/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Samples;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yunac
 */
public class admin_crud_2 extends javax.swing.JFrame {

    
    
    
    
    public admin_crud_2() {
        initComponents();
        Connect();
        LoadProductNo();
        Fetch();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
                                                                   //change local host here
            con = DriverManager.getConnection("jdbc:mysql://localhost/user_acc","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LoadProductNo(){
        try {
            pst = con.prepareStatement("SELECT id FROM user_db");
            rs = pst.executeQuery();
            txtID.removeAllItems();
            while(rs.next()){
                txtID.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Fetch(){
        try {
            int q;
            pst = con.prepareStatement("SELECT * FROM user_db");
            rs = pst.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            q = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1; a<=q; a++){
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("student_id"));
                    v2.add(rs.getString("first_name"));
                    v2.add(rs.getString("last_name"));
                    v2.add(rs.getString("nu_email"));
                }
                df.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        studentID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JComboBox();
        nuEMAIL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productcrudbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, -1, -1));

        firstName.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 47, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lastName.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 260, 40));

        studentID.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Student ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        submitButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        updateButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, 30));

        deleteButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, 30));

        clearButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        searchButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 94, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 560, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Student ID", "First Name", "Last Name", "NU Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 560, 390));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 560, 390));

        txtID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 160, 40));

        nuEMAIL.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        getContentPane().add(nuEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 260, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("NU Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        productcrudbtn.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        productcrudbtn.setText("Product Crud Operation");
        productcrudbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productcrudbtnActionPerformed(evt);
            }
        });
        getContentPane().add(productcrudbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 270, 30));

        setSize(new java.awt.Dimension(614, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
        try {
            
            String student_id = studentID.getText();
            String first_name = firstName.getText();
            String last_name = lastName.getText();
            String nu_email = nuEMAIL.getText();
            
            pst = con.prepareStatement("INSERT INTO user_db (student_id,first_name,last_name,nu_email)VALUES (?,?,?,?)");
            pst.setString(1, student_id);
            pst.setString(2, first_name);
            pst.setString(3, last_name);
            pst.setString(4, nu_email);
            
            int k = pst.executeUpdate();
            
            if (k==1) {
                JOptionPane.showMessageDialog(this, "Sucessfully Added!");
                firstName.setText("");
                lastName.setText("");
                studentID.setText("");
                nuEMAIL.setText("");
                Fetch();
                LoadProductNo();
                
            }else{
                JOptionPane.showMessageDialog(this, "Record failed!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        firstName.setText("");
        lastName.setText("");
        studentID.setText("");
        nuEMAIL.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            String pid = txtID.getSelectedItem().toString();
            
            pst = con.prepareStatement("SELECT * FROM user_db WHERE id=?");
            pst.setString(1, pid);
            rs=pst.executeQuery();
            
            if (rs.next()==true) {
                firstName.setText(rs.getString(2));
                lastName.setText(rs.getString(3));
                studentID.setText(rs.getString(4));
                nuEMAIL.setText(rs.getString(5));
            } else {
                 JOptionPane.showMessageDialog(this, "No Record Found!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String student_id = studentID.getText();
            String first_name = firstName.getText();
            String last_name = lastName.getText();
            String nu_email = nuEMAIL.getText();
            String sid = txtID.getSelectedItem().toString();

            pst = con.prepareStatement("UPDATE user_db SET first_name=?, last_name=?, student_ud=?, nu_email=? WHERE id=?");

            pst.setString(1, student_id);
            pst.setString(2, first_name);
            pst.setString(3, last_name);
            pst.setString(4, sid);
            pst.setString(5, nu_email);

            int k = pst.executeUpdate();
            if (k==1) {
                JOptionPane.showMessageDialog(this, "Record has been successfully updated!");
                firstName.setText("");
                lastName.setText("");
                studentID.setText("");
                nuEMAIL.setText("");
                firstName.requestFocus();
                Fetch();
                LoadProductNo();
            }

        } catch (SQLException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            
            String sid = txtID.getSelectedItem().toString();
            pst = con.prepareStatement("DELETE FROM user_db WHERE id=?");
            pst.setString(1, sid);

            int k = pst.executeUpdate();
            if (k==1) {
                JOptionPane.showMessageDialog(this, "Record has been successfully deleted!");
                firstName.setText("");
                lastName.setText("");
                studentID.setText("");
                nuEMAIL.setText("");
                firstName.requestFocus();
                Fetch();
                LoadProductNo();
            }else{
                JOptionPane.showMessageDialog(this, "Record failed to delete!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(admin_crud_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void productcrudbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productcrudbtnActionPerformed
        this.dispose();
        products_crudsystem pc = new products_crudsystem();
        pc.setVisible(true);
    }//GEN-LAST:event_productcrudbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_crud_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_crud_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_crud_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_crud_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_crud_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField nuEMAIL;
    private javax.swing.JButton productcrudbtn;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField studentID;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox txtID;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
