/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Samples;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yunac
 */
public class products_crudsystem extends javax.swing.JFrame {

    
    
    
    
    public products_crudsystem() {
        initComponents();
        Connect();
        LoadProductNo();
        Fetch();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
                                                                   //change local host here
            con = DriverManager.getConnection("jdbc:mysql://localhost/java_users_db","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LoadProductNo(){
        try {
            pst = con.prepareStatement("SELECT id FROM users");
            rs = pst.executeQuery();
            txtID.removeAllItems();
            while(rs.next()){
                txtID.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Fetch(){
        try {
            int q;
            pst = con.prepareStatement("SELECT * FROM users");
            rs = pst.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            q = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1; a<=q; a++){
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("product_name"));
                    v2.add(rs.getString("product_price"));
                    v2.add(rs.getString("product_quantity"));
                }
                df.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        productQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtID = new javax.swing.JComboBox();
        admincrudbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Product Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, -1, -1));

        productName.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        getContentPane().add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 47, 400, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Product Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 95, -1, -1));

        productPrice.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        getContentPane().add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 121, 400, 30));

        productQuantity.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        getContentPane().add(productQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 195, 400, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Product Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 169, -1, -1));

        submitButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 243, 90, -1));

        updateButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 243, 90, -1));

        deleteButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 243, 90, -1));

        clearButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 243, 94, -1));

        searchButton.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 94, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 402, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Product Price", "Product Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 400, 330));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 400, 330));

        txtID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 40));

        admincrudbtn.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        admincrudbtn.setText("Admin Crud");
        admincrudbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admincrudbtnActionPerformed(evt);
            }
        });
        getContentPane().add(admincrudbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 281, 94, 40));

        setSize(new java.awt.Dimension(453, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
        try {
            
            String product_name = productName.getText();
            String product_price = productPrice.getText();
            String product_quantity = productQuantity.getText();
            
            pst = con.prepareStatement("INSERT INTO users (product_name,product_price,product_quantity)VALUES (?,?,?)");
            pst.setString(1, product_name);
            pst.setString(2, product_price);
            pst.setString(3, product_quantity);
            
            int k = pst.executeUpdate();
            
            if (k==1) {
                JOptionPane.showMessageDialog(this, "Sucessfully Added!");
                productName.setText("");
                productPrice.setText("");
                productQuantity.setText("");
                Fetch();
                LoadProductNo();
                
            }else{
                JOptionPane.showMessageDialog(this, "Record failed!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        productName.setText("");
        productPrice.setText("");
        productQuantity.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        try {
            String pid = txtID.getSelectedItem().toString();
            
            pst = con.prepareStatement("SELECT * FROM users WHERE id=?");
            pst.setString(1, pid);
            rs=pst.executeQuery();
            
            if (rs.next()==true) {
                productName.setText(rs.getString(2));
                productPrice.setText(rs.getString(3));
                productQuantity.setText(rs.getString(4));
            } else {
                 JOptionPane.showMessageDialog(this, "No Record Found!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String product_name = productName.getText();
            String product_price = productPrice.getText();
            String product_quantity = productQuantity.getText();
            String pid = txtID.getSelectedItem().toString();

            pst = con.prepareStatement("UPDATE users SET product_name=?, product_price=?, product_quantity=? WHERE id=?");

            pst.setString(1, product_name);
            pst.setString(2, product_price);
            pst.setString(3, product_quantity);
            pst.setString(4, pid);

            int k = pst.executeUpdate();
            if (k==1) {
                JOptionPane.showMessageDialog(this, "Record has been successfully updated!");
                productName.setText("");
                productPrice.setText("");
                productQuantity.setText("");
                productName.requestFocus();
                Fetch();
                LoadProductNo();
            }

        } catch (SQLException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            
            String pid = txtID.getSelectedItem().toString();
            pst = con.prepareStatement("DELETE FROM users WHERE id=?");
            pst.setString(1, pid);

            int k = pst.executeUpdate();
            if (k==1) {
                JOptionPane.showMessageDialog(this, "Record has been successfully deleted!");
                productName.setText("");
                productPrice.setText("");
                productQuantity.setText("");
                productName.requestFocus();
                Fetch();
                LoadProductNo();
            }else{
                JOptionPane.showMessageDialog(this, "Record failed to delete!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(products_crudsystem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void admincrudbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admincrudbtnActionPerformed
        this.dispose();
        admin_crud_2 ac2 = new admin_crud_2();
        ac2.setVisible(true);
    }//GEN-LAST:event_admincrudbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(products_crudsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(products_crudsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(products_crudsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(products_crudsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admincrudbtn;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JTextField productQuantity;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox txtID;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
